name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] 

  workflow_dispatch:

permissions:
  contents: write 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v7

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x' 

    - name: Publish
      working-directory: ${{ github.workspace }}/src/client/StreamSharp/
      run: dotnet publish ./StreamSharp.csproj -c Release -o ${{ github.workspace }}/release /p:BlazorEnableCompression=false

    - name: Setup base path
      run: |
        sed -i 's/<base href="\/" \/>/<base href="\/StreamSharp\/" \/>/g' ${{ github.workspace }}/release/wwwroot/index.html
        touch ${{ github.workspace }}/release/wwwroot/.nojekyll
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{ github.workspace }}/release/wwwroot 
        branch: gh-pages 
        clean: true 